//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Applications')
export class ApplicationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  applicationName: string;

  @Column('text', { nullable: true })
  applicationIndustry: string;

  @Column('text', { nullable: true })
  applicationDescription: string;

  @Column('text', { nullable: true })
  applicationFeatures: string;

  @Column('text', { nullable: true })
  applicationStatus: string;
}
