//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Authors')
export class AuthorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  authorName: string;

  @Column('text', { nullable: true })
  genre: string;

  @Column('text', { nullable: true })
  nationality: string;
}
