//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Book')
export class BookEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('integer', { nullable: true })
  author: number;

  @Column('date', { nullable: true })
  releaseDate: Date;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  ISBN: string;

  @Column('text', { nullable: true })
  coverImage: string;

  @Column('text', { nullable: true })
  publisher: string;

  @Column('text', { nullable: true })
  language: string;

  @Column('integer', { nullable: true })
  pages: number;

  @Column('real', { nullable: true })
  averageRating: number;
}
