//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Clients')
export class ClientsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Industry: string;

  @Column('text', { nullable: true })
  ContactName: string;

  @Column('text', { nullable: true })
  ContactEmail: string;

  @Column('text', { nullable: true })
  ContactPhone: string;

  @Column('text', { nullable: true })
  Address: string;
}
