//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Consultants')
export class ConsultantsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Phone: string;

  @Column('text', { nullable: true })
  Specialization: string;

  @Column('date', { nullable: true })
  HireDate: Date;

  @Column('text', { nullable: true })
  Status: string;
}
