//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Contests')
export class ContestsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  year: number;

  @Column('text', { nullable: true })
  location: string;

  @Column('text', { nullable: true })
  hostcountry: string;
}
