//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Engagements')
export class EngagementsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('date', { nullable: true })
  StartDate: Date;

  @Column('date', { nullable: true })
  EndDate: Date;

  @Column('integer', { nullable: true })
  ConsultantID: number;

  @Column('integer', { nullable: true })
  ClientID: number;

  @Column('integer', { nullable: true })
  ServiceID: number;

  @Column('text', { nullable: true })
  Status: string;
}
