//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Eventrecipe')
export class EventrecipeEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  modifications: string;

  @Column('integer', { nullable: true })
  rating: number;

  @Column('text', { nullable: true })
  notes: string;
}
