//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Event')
export class EventEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('date', { nullable: true })
  eventDate: Date;

  @Column('text', { nullable: true })
  location: string;

  @Column('text', { nullable: true })
  notes: string;
}
