//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Funds')
export class FundsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  FundName: string;

  @Column('text', { nullable: true })
  FundManager: string;

  @Column('text', { nullable: true })
  FundType: string;

  @Column('text', { nullable: true })
  FundDescription: string;

  @Column('date', { nullable: true })
  FundStartDate: Date;

  @Column('real', { nullable: true })
  FundSize: number;

  @Column('text', { nullable: true })
  FundStatus: string;
}
