//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Home')
export class HomeEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  address: string;

  @Column('text', { nullable: true })
  name: string;

  @Column('integer', { nullable: true })
  owner: number;
}
