//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Investors')
export class InvestorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  InvestorName: string;

  @Column('text', { nullable: true })
  InvestorType: string;

  @Column('text', { nullable: true })
  InvestorContact: string;

  @Column('text', { nullable: true })
  InvestorAddress: string;

  @Column('real', { nullable: true })
  InvestorInvestmentAmount: number;

  @Column('date', { nullable: true })
  InvestorInvestmentDate: Date;

  @Column('text', { nullable: true })
  InvestorStatus: string;
}
