//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Log')
export class LogEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  waterHeater: number;

  @Column('date', { nullable: true })
  timestamp: Date;

  @Column('text', { nullable: true })
  status: string;

  @Column('real', { nullable: true })
  temperature: number;

  @Column('text', { nullable: true })
  errorCodes: string;

  @Column('text', { nullable: true })
  settingName: string;

  @Column('text', { nullable: true })
  oldValue: string;

  @Column('text', { nullable: true })
  newValue: string;
}
