//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Members')
export class MembersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Address: string;

  @Column('text', { nullable: true })
  PhoneNumber: string;

  @Column('date', { nullable: true })
  DateOfBirth: Date;

  @Column('text', { nullable: true })
  MembershipStatus: string;

  @Column('date', { nullable: true })
  JoiningDate: Date;

  @Column('text', { nullable: true })
  MembershipType: string;
}
