//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Player')
export class PlayerEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('integer', { nullable: true })
  Age: number;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Username: string;
}
