//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Recipe')
export class RecipeEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  ingredients: string;

  @Column('text', { nullable: true })
  instructions: string;

  @Column('integer', { nullable: true })
  preparationTime: number;

  @Column('integer', { nullable: true })
  servings: number;
}
