//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Timersetting')
export class TimersettingEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  waterHeater: number;

  @Column('date', { nullable: true })
  startTime: Date;

  @Column('date', { nullable: true })
  endTime: Date;

  @Column('text', { nullable: true })
  daysOfWeek: string;

  @Column('real', { nullable: true })
  targetTemperature: number;
}
