//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  TransactionID: number;

  @Column('date', { nullable: true })
  TransactionDate: Date;

  @Column('text', { nullable: true })
  TransactionType: string;

  @Column('real', { nullable: true })
  TransactionAmount: number;

  @Column('integer', { nullable: true })
  TransactionFund: number;

  @Column('integer', { nullable: true })
  TransactionInvestor: number;

  @Column('text', { nullable: true })
  TransactionDescription: string;
}
