//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Votes')
export class VotesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  fromCountry: string;

  @Column('integer', { nullable: true })
  toParticipant: number;

  @Column('integer', { nullable: true })
  points: number;

  @Column('integer', { nullable: true })
  contest: number;
}
