//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Waterheater')
export class WaterheaterEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  serialNumber: string;

  @Column('text', { nullable: true })
  model: string;

  @Column('date', { nullable: true })
  installationDate: Date;

  @Column('integer', { nullable: true })
  home: number;

  @Column('text', { nullable: true })
  firmwareVersion: string;

  @Column('text', { nullable: true })
  appVersion: string;

  @Column('date', { nullable: true })
  lastSeenOn: Date;
}
