//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { ContestsEntity } from './db/Contests.entity';
import { ParticipantsEntity } from './db/Participants.entity';
import { VotesEntity } from './db/Votes.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      ContestsEntity,
      ParticipantsEntity,
      VotesEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Contests: [
        { year: 2023, location: 'Liverpool', hostcountry: 'United Kingdom' },
        { year: 2022, location: 'Turin', hostcountry: 'Italy' },
        { year: 2021, location: 'Rotterdam', hostcountry: 'Netherlands' },
        { year: 2019, location: 'Tel Aviv', hostcountry: 'Israel' },
        { year: 2018, location: 'Lisbon', hostcountry: 'Portugal' },
      ],
      Participants: [
        {
          artist: 'Loreen',
          country: 'Sweden',
          songTitle: 'Tattoo',
          contest: 1,
          qualificationLevel: 'Final',
          score: 583,
          rank: 1,
        },
        {
          artist: 'Marco Mengoni',
          country: 'Italy',
          songTitle: 'Due Vite',
          contest: 1,
          qualificationLevel: 'Final',
          score: 350,
          rank: 4,
        },
        {
          artist: 'Noa Kirel',
          country: 'Israel',
          songTitle: 'Unicorn',
          contest: 2,
          qualificationLevel: 'Final',
          score: 362,
          rank: 3,
        },
        {
          artist: 'Blanca Paloma',
          country: 'Spain',
          songTitle: 'Eaea',
          contest: 2,
          qualificationLevel: 'Final',
          score: 100,
          rank: 17,
        },
        {
          artist: 'Käärijä',
          country: 'Finland',
          songTitle: 'Cha Cha Cha',
          contest: 3,
          qualificationLevel: 'Final',
          score: 526,
          rank: 2,
        },
      ],
      Votes: [
        {
          name: 'Jury Vote',
          fromCountry: 'Sweden',
          toParticipant: 2,
          points: 12,
          contest: 1,
        },
        {
          name: 'Televote',
          fromCountry: 'Italy',
          toParticipant: 3,
          points: 10,
          contest: 2,
        },
        {
          name: 'Jury Vote',
          fromCountry: 'France',
          toParticipant: 1,
          points: 8,
          contest: 3,
        },
        {
          name: 'Televote',
          fromCountry: 'Germany',
          toParticipant: 4,
          points: 7,
          contest: 4,
        },
        {
          name: 'Jury Vote',
          fromCountry: 'Spain',
          toParticipant: 5,
          points: 6,
          contest: 5,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('ContestsEntity', data.Contests);
      await this.SeedResource('ParticipantsEntity', data.Participants);
      await this.SeedResource('VotesEntity', data.Votes);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
