//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { BookEntity } from './db/Book.entity';
import { AuthorsEntity } from './db/Authors.entity';
import { MembersEntity } from './db/Members.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      BookEntity,
      AuthorsEntity,
      MembersEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Book: [
        {
          title: 'The Great Gatsby',
          author: 1,
          releaseDate: '1925-04-10T00:00:00Z',
          description:
            'A novel about the themes of resistance to change, decadence, and the American Dream.',
          ISBN: '9780743273565',
          coverImage: 'https://example.com/images/greatgatsby.jpg',
          publisher: "Charles Scribner's Sons",
          language: 'English',
          pages: 218,
          averageRating: 3.9,
        },
        {
          title: '1984',
          author: 2,
          releaseDate: '1949-06-08T00:00:00Z',
          description:
            'A dystopian social science fiction novel and cautionary tale.',
          ISBN: '9780451524935',
          coverImage: 'https://example.com/images/1984.jpg',
          publisher: 'Secker & Warburg',
          language: 'English',
          pages: 328,
          averageRating: 4.2,
        },
        {
          title: 'To Kill a Mockingbird',
          author: 3,
          releaseDate: '1960-07-11T00:00:00Z',
          description: 'A novel about racial injustice in the American South.',
          ISBN: '9780061120084',
          coverImage: 'https://example.com/images/tokillamockingbird.jpg',
          publisher: 'J. B. Lippincott & Co.',
          language: 'English',
          pages: 281,
          averageRating: 4.3,
        },
        {
          title: 'The Catcher in the Rye',
          author: 4,
          releaseDate: '1951-07-16T00:00:00Z',
          description:
            'A novel about teenage alienation and loss of innocence.',
          ISBN: '9780316769488',
          coverImage: 'https://example.com/images/catcherintherye.jpg',
          publisher: 'Little, Brown and Company',
          language: 'English',
          pages: 234,
          averageRating: 3.8,
        },
        {
          title: 'Pride and Prejudice',
          author: 5,
          releaseDate: '1813-01-28T00:00:00Z',
          description: 'A romantic novel of manners.',
          ISBN: '9780679783268',
          coverImage: 'https://example.com/images/prideandprejudice.jpg',
          publisher: 'T. Egerton, Whitehall',
          language: 'English',
          pages: 432,
          averageRating: 4.5,
        },
      ],
      Authors: [
        {
          authorName: 'J.K. Rowling',
          genre: 'Fantasy',
          nationality: 'British',
        },
        {
          authorName: 'Haruki Murakami',
          genre: 'Magical Realism',
          nationality: 'Japanese',
        },
        {
          authorName: 'Toni Morrison',
          genre: 'Literary Fiction',
          nationality: 'American',
        },
        {
          authorName: 'Gabriel García Márquez',
          genre: 'Magical Realism',
          nationality: 'Colombian',
        },
        {
          authorName: 'Isabel Allende',
          genre: 'Historical Fiction',
          nationality: 'Chilean',
        },
      ],
      Members: [
        {
          Name: 'Alex Johnson',
          Email: 'alex.johnson@example.com',
          Address: '123 Maple Street, Springfield',
          PhoneNumber: '555-1234',
          DateOfBirth: '1985-07-12T00:00:00Z',
          MembershipStatus: 'Active',
          JoiningDate: '2020-01-15T00:00:00Z',
          MembershipType: 'Premium',
        },
        {
          Name: 'Bethany Hughes',
          Email: 'bethany.h@example.com',
          Address: '456 Oak Avenue, Riverdale',
          PhoneNumber: '555-5678',
          DateOfBirth: '1992-11-08T00:00:00Z',
          MembershipStatus: 'Inactive',
          JoiningDate: '2021-05-22T00:00:00Z',
          MembershipType: 'Standard',
        },
        {
          Name: 'Carlos Gomez',
          Email: 'carlos.gomez@example.com',
          Address: '789 Pine Road, Lakeside',
          PhoneNumber: '555-9101',
          DateOfBirth: '1978-03-24T00:00:00Z',
          MembershipStatus: 'Active',
          JoiningDate: '2019-09-10T00:00:00Z',
          MembershipType: 'Basic',
        },
        {
          Name: 'Diana Smith',
          Email: 'diana.smith@example.com',
          Address: '1011 Birch Lane, Hilltown',
          PhoneNumber: '555-1213',
          DateOfBirth: '1988-06-15T00:00:00Z',
          MembershipStatus: 'Active',
          JoiningDate: '2022-02-28T00:00:00Z',
          MembershipType: 'Premium',
        },
        {
          Name: 'Evan Wright',
          Email: 'evan.wright@example.com',
          Address: '1213 Cedar Path, Seaview',
          PhoneNumber: '555-1415',
          DateOfBirth: '1990-09-30T00:00:00Z',
          MembershipStatus: 'Suspended',
          JoiningDate: '2021-07-04T00:00:00Z',
          MembershipType: 'Standard',
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('BookEntity', data.Book);
      await this.SeedResource('AuthorsEntity', data.Authors);
      await this.SeedResource('MembersEntity', data.Members);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
