//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { HomeEntity } from './db/Home.entity';
import { WaterheaterEntity } from './db/Waterheater.entity';
import { LogEntity } from './db/Log.entity';
import { TimersettingEntity } from './db/Timersetting.entity';
import { UserEntity } from './db/User.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      HomeEntity,
      WaterheaterEntity,
      LogEntity,
      TimersettingEntity,
      UserEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Home: [
        {
          address: '123 Maple Street, Springfield',
          name: 'Maple Residence',
          owner: 1,
        },
        { address: '456 Oak Avenue, Rivertown', name: 'Oak Villa', owner: 2 },
        { address: '789 Pine Lane, Lakeside', name: 'Pine Retreat', owner: 3 },
        {
          address: '321 Birch Road, Hillcrest',
          name: 'Birch Cottage',
          owner: 4,
        },
        {
          address: '654 Cedar Drive, Brookfield',
          name: 'Cedar House',
          owner: 5,
        },
      ],
      Waterheater: [
        {
          serialNumber: 'WH-2024-001',
          model: 'EcoHeat 3000',
          installationDate: '2023-02-15T10:30:00Z',
          home: 1,
          firmwareVersion: '1.2.5',
          appVersion: '2.0.1',
          lastSeenOn: '2024-06-12T08:45:00Z',
        },
        {
          serialNumber: 'WH-2023-014',
          model: 'ThermoPro X',
          installationDate: '2022-11-03T14:00:00Z',
          home: 2,
          firmwareVersion: '1.1.9',
          appVersion: '1.9.8',
          lastSeenOn: '2024-06-11T21:10:00Z',
        },
        {
          serialNumber: 'WH-2022-087',
          model: 'AquaSafe 200',
          installationDate: '2021-07-22T09:15:00Z',
          home: 3,
          firmwareVersion: '1.0.7',
          appVersion: '1.8.3',
          lastSeenOn: '2024-06-12T06:20:00Z',
        },
        {
          serialNumber: 'WH-2024-042',
          model: 'HydroMax Plus',
          installationDate: '2024-01-10T16:45:00Z',
          home: 4,
          firmwareVersion: '2.0.0',
          appVersion: '2.1.0',
          lastSeenOn: '2024-06-12T09:00:00Z',
        },
        {
          serialNumber: 'WH-2023-055',
          model: 'EcoHeat 3000',
          installationDate: '2023-05-18T13:25:00Z',
          home: 5,
          firmwareVersion: '1.2.5',
          appVersion: '2.0.1',
          lastSeenOn: '2024-06-11T19:30:00Z',
        },
      ],
      Log: [
        {
          waterHeater: 2,
          timestamp: '2024-06-15T08:30:00Z',
          status: 'Active',
          temperature: 54.2,
          errorCodes: '',
          settingName: 'Target Temperature',
          oldValue: '50',
          newValue: '55',
        },
        {
          waterHeater: 1,
          timestamp: '2024-06-15T06:45:00Z',
          status: 'Idle',
          temperature: 48.7,
          errorCodes: 'E02',
          settingName: 'Timer',
          oldValue: '06:00-08:00',
          newValue: '06:00-09:00',
        },
        {
          waterHeater: 3,
          timestamp: '2024-06-14T22:10:00Z',
          status: 'Error',
          temperature: 42,
          errorCodes: 'E05',
          settingName: 'Mode',
          oldValue: 'Eco',
          newValue: 'Boost',
        },
        {
          waterHeater: 4,
          timestamp: '2024-06-15T12:00:00Z',
          status: 'Active',
          temperature: 60.5,
          errorCodes: '',
          settingName: 'Firmware Version',
          oldValue: '1.2.3',
          newValue: '1.2.4',
        },
        {
          waterHeater: 5,
          timestamp: '2024-06-15T09:20:00Z',
          status: 'Maintenance',
          temperature: 35,
          errorCodes: 'E01,E03',
          settingName: 'App Version',
          oldValue: '2.0.0',
          newValue: '2.1.0',
        },
      ],
      Timersetting: [
        {
          waterHeater: 1,
          startTime: '2024-06-10T05:30:00Z',
          endTime: '2024-06-10T07:00:00Z',
          daysOfWeek: 'Monday,Wednesday,Friday',
          targetTemperature: 55,
        },
        {
          waterHeater: 2,
          startTime: '2024-06-10T18:00:00Z',
          endTime: '2024-06-10T20:00:00Z',
          daysOfWeek: 'Tuesday,Thursday',
          targetTemperature: 60,
        },
        {
          waterHeater: 3,
          startTime: '2024-06-11T06:00:00Z',
          endTime: '2024-06-11T08:30:00Z',
          daysOfWeek: 'Saturday,Sunday',
          targetTemperature: 50.5,
        },
        {
          waterHeater: 4,
          startTime: '2024-06-10T21:00:00Z',
          endTime: '2024-06-10T22:30:00Z',
          daysOfWeek: 'Monday,Tuesday,Wednesday,Thursday,Friday',
          targetTemperature: 57.5,
        },
        {
          waterHeater: 5,
          startTime: '2024-06-11T04:45:00Z',
          endTime: '2024-06-11T06:15:00Z',
          daysOfWeek: 'Sunday',
          targetTemperature: 53,
        },
      ],
      User: [
        {
          name: 'Alice Johnson',
          email: 'alice.johnson@example.com',
          password: 'A1ic3J!2024',
          role: 'homeowner',
        },
        {
          name: 'Bob Smith',
          email: 'bob.smith@example.com',
          password: 'B0bSm!th#456',
          role: 'admin',
        },
        {
          name: 'Carol Lee',
          email: 'carol.lee@example.com',
          password: 'C@r0lL33pw',
          role: 'user',
        },
        {
          name: 'David Patel',
          email: 'david.patel@example.com',
          password: 'Dav1dP@t3l!',
          role: 'technician',
        },
        {
          name: 'Emma Garcia',
          email: 'emma.garcia@example.com',
          password: 'Emm@Garc!a22',
          role: 'user',
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('HomeEntity', data.Home);
      await this.SeedResource('WaterheaterEntity', data.Waterheater);
      await this.SeedResource('LogEntity', data.Log);
      await this.SeedResource('TimersettingEntity', data.Timersetting);
      await this.SeedResource('UserEntity', data.User);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
