//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const BookTitle = () => {
  const record = useRecordContext();
  return <span>Book {record ? `"${record.title}"` : ''}</span>;
};

export const BookList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="title" />
      <ReferenceField source="author" reference="Authors" />
      <DateField source="releaseDate" />
      <TextField source="description" />
      <TextField source="ISBN" />
      <ImageField source="coverImage" />
      <TextField source="publisher" />
      <TextField source="language" />
      <NumberField source="pages" />
      <NumberField source="averageRating" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const BookEdit = () => (
  <Edit title={<BookTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="author" reference="Authors" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="releaseDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ISBN" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="coverImage" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="publisher" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="language" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="pages" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="averageRating" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const BookCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="author" reference="Authors" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="releaseDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="description" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ISBN" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="coverImage" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="publisher" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="language" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="pages" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="averageRating" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="author"
    label="author"
    reference="Authors"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
