//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EngagementsTitle = () => {
  const record = useRecordContext();
  return <span>Engagements {record ? `"${record.Title}"` : ''}</span>;
};

export const EngagementsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="Title" />
      <TextField source="Description" />
      <DateField source="StartDate" />
      <DateField source="EndDate" />
      <ReferenceField source="ConsultantID" reference="Consultants" />
      <ReferenceField source="ClientID" reference="Clients" />
      <ReferenceField source="ServiceID" reference="Services" />
      <TextField source="Status" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EngagementsEdit = () => (
  <Edit title={<EngagementsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ConsultantID" reference="Consultants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ClientID" reference="Clients" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ServiceID" reference="Services" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EngagementsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="StartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="EndDate" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ConsultantID" reference="Consultants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ClientID" reference="Clients" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="ServiceID" reference="Services" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="ConsultantID"
    label="ConsultantID"
    reference="Consultants"
    alwaysOn
  />,
  <ReferenceInput
    source="ClientID"
    label="ClientID"
    reference="Clients"
    alwaysOn
  />,
  <ReferenceInput
    source="ServiceID"
    label="ServiceID"
    reference="Services"
    alwaysOn
  />,
  ,
];
