//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const FundsTitle = () => {
  const record = useRecordContext();
  return <span>Funds {record ? `"${record.id}"` : ''}</span>;
};

export const FundsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="FundName" />
      <TextField source="FundManager" />
      <TextField source="FundType" />
      <TextField source="FundDescription" />
      <DateField source="FundStartDate" />
      <NumberField source="FundSize" />
      <TextField source="FundStatus" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const FundsEdit = () => (
  <Edit title={<FundsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="FundName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundManager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundDescription" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="FundStartDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="FundSize" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const FundsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="FundName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundManager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundDescription" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="FundStartDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="FundSize" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FundStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
