//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const GameSessionTitle = () => {
  const record = useRecordContext();
  return <span>GameSession {record ? `"${record.Date}"` : ''}</span>;
};

export const GameSessionList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="Game" reference="Game" />
      <ReferenceField source="Players" reference="Player" />
      <DateField source="Date" />
      <NumberField source="Duration" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const GameSessionEdit = () => (
  <Edit title={<GameSessionTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="Game" reference="Game" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Players" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="Date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Duration" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const GameSessionCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="Game" reference="Game" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Players" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="Date" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Duration" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput source="Game" label="Game" reference="Game" alwaysOn />,
  <ReferenceInput
    source="Players"
    label="Players"
    reference="Player"
    alwaysOn
  />,
  ,
  ,
];
