//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ScoreTitle = () => {
  const record = useRecordContext();
  return <span>Score {record ? `"${record.id}"` : ''}</span>;
};

export const ScoreList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="gameSession" reference="Gamesession" />
      <ReferenceField source="player" reference="Player" />
      <NumberField source="scoreValue" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ScoreEdit = () => (
  <Edit title={<ScoreTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="gameSession" reference="Gamesession" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="scoreValue" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ScoreCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="gameSession" reference="Gamesession" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player" reference="Player" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="scoreValue" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="gameSession"
    label="gameSession"
    reference="Gamesession"
    alwaysOn
  />,
  <ReferenceInput source="player" label="player" reference="Player" alwaysOn />,
  ,
];
