//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const TimersettingTitle = () => {
  const record = useRecordContext();
  return <span>Timersetting {record ? `"${record.id}"` : ''}</span>;
};

export const TimersettingList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="waterHeater" reference="Waterheater" />
      <DateField source="startTime" />
      <DateField source="endTime" />
      <TextField source="daysOfWeek" />
      <NumberField source="targetTemperature" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const TimersettingEdit = () => (
  <Edit title={<TimersettingTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="waterHeater" reference="Waterheater" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="daysOfWeek" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="targetTemperature" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const TimersettingCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="waterHeater" reference="Waterheater" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startTime" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="daysOfWeek" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="targetTemperature" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="waterHeater"
    label="waterHeater"
    reference="Waterheater"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
];
