//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { FundsList, FundsCreate, FundsEdit } from './resources/Funds';
import {
  InvestorsList,
  InvestorsCreate,
  InvestorsEdit,
} from './resources/Investors';
import {
  TransactionsList,
  TransactionsCreate,
  TransactionsEdit,
} from './resources/Transactions';
import {
  ApplicationsList,
  ApplicationsCreate,
  ApplicationsEdit,
} from './resources/Applications';
import FundsIcon from '@mui/icons-material/AccountBalance';
import InvestorsIcon from '@mui/icons-material/PeopleAlt';
import TransactionsIcon from '@mui/icons-material/SwapHoriz';
import ApplicationsIcon from '@mui/icons-material/Apps';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/af5c54068">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Funds"
          options={{ label: 'Funds' }}
          list={FundsList}
          create={FundsCreate}
          edit={FundsEdit}
          recordRepresentation="id"
          icon={FundsIcon}
        />
        <Resource
          name="Investors"
          options={{ label: 'Investors' }}
          list={InvestorsList}
          create={InvestorsCreate}
          edit={InvestorsEdit}
          recordRepresentation="id"
          icon={InvestorsIcon}
        />
        <Resource
          name="Transactions"
          options={{ label: 'Transactions' }}
          list={TransactionsList}
          create={TransactionsCreate}
          edit={TransactionsEdit}
          recordRepresentation="id"
          icon={TransactionsIcon}
        />
        <Resource
          name="Applications"
          options={{ label: 'Applications' }}
          list={ApplicationsList}
          create={ApplicationsCreate}
          edit={ApplicationsEdit}
          recordRepresentation="id"
          icon={ApplicationsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
