//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  EngagementsList,
  EngagementsCreate,
  EngagementsEdit,
} from './resources/Engagements';
import {
  ConsultantsList,
  ConsultantsCreate,
  ConsultantsEdit,
} from './resources/Consultants';
import { ClientsList, ClientsCreate, ClientsEdit } from './resources/Clients';
import {
  ServicesList,
  ServicesCreate,
  ServicesEdit,
} from './resources/Services';
import EngagementsIcon from '@mui/icons-material/Assignment';
import ConsultantsIcon from '@mui/icons-material/People';
import ClientsIcon from '@mui/icons-material/BusinessCenter';
import ServicesIcon from '@mui/icons-material/DesignServices';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/af5c54068">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Engagements"
          options={{ label: 'Engagements' }}
          list={EngagementsList}
          create={EngagementsCreate}
          edit={EngagementsEdit}
          recordRepresentation="Title"
          icon={EngagementsIcon}
        />
        <Resource
          name="Consultants"
          options={{ label: 'Consultants' }}
          list={ConsultantsList}
          create={ConsultantsCreate}
          edit={ConsultantsEdit}
          recordRepresentation="Name"
          icon={ConsultantsIcon}
        />
        <Resource
          name="Clients"
          options={{ label: 'Clients' }}
          list={ClientsList}
          create={ClientsCreate}
          edit={ClientsEdit}
          recordRepresentation="Name"
          icon={ClientsIcon}
        />
        <Resource
          name="Services"
          options={{ label: 'Services' }}
          list={ServicesList}
          create={ServicesCreate}
          edit={ServicesEdit}
          recordRepresentation="Name"
          icon={ServicesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
