//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Recipe: [
      {
        name: 'Classic Lasagna',
        description:
          'A hearty Italian dish layered with rich meat sauce, creamy béchamel, and melted cheese.',
        ingredients:
          'Lasagna noodles, ground beef, tomato sauce, onion, garlic, ricotta cheese, mozzarella cheese, parmesan cheese, olive oil, salt, pepper, basil, oregano',
        instructions:
          '1. Preheat oven to 375°F (190°C). 2. Cook noodles according to package instructions. 3. In a skillet, sauté onion and garlic in olive oil, add ground beef and cook until browned. 4. Stir in tomato sauce and herbs, simmer for 20 minutes. 5. Layer noodles, meat sauce, ricotta, and mozzarella in a baking dish. 6. Repeat layers and top with parmesan. 7. Bake for 45 minutes. 8. Let rest before serving.',
        preparationTime: 90,
        servings: 8,
      },
      {
        name: 'Lemon Herb Roast Chicken',
        description:
          'Tender roast chicken infused with fresh lemon and aromatic herbs, perfect for family dinners.',
        ingredients:
          'Whole chicken, lemon, garlic, rosemary, thyme, olive oil, salt, pepper',
        instructions:
          '1. Preheat oven to 400°F (200°C). 2. Rub chicken with olive oil, salt, and pepper. 3. Stuff cavity with lemon halves, garlic, and herbs. 4. Roast for 1 hour 15 minutes or until juices run clear. 5. Let rest 10 minutes before carving.',
        preparationTime: 90,
        servings: 6,
      },
      {
        name: 'Vegetarian Chili',
        description:
          'A spicy and satisfying chili packed with beans, vegetables, and bold flavors.',
        ingredients:
          'Kidney beans, black beans, bell pepper, onion, garlic, diced tomatoes, corn, chili powder, cumin, paprika, olive oil, salt, pepper',
        instructions:
          '1. Heat olive oil in a large pot. 2. Sauté onion, garlic, and bell pepper until soft. 3. Add spices and cook for 1 minute. 4. Stir in beans, tomatoes, and corn. 5. Simmer for 30 minutes, stirring occasionally. 6. Serve hot.',
        preparationTime: 45,
        servings: 5,
      },
      {
        name: 'Chocolate Chip Cookies',
        description:
          'Chewy, golden cookies loaded with gooey chocolate chips—an all-time favorite treat.',
        ingredients:
          'All-purpose flour, butter, sugar, brown sugar, eggs, vanilla extract, baking soda, salt, chocolate chips',
        instructions:
          '1. Preheat oven to 350°F (175°C). 2. Cream butter and sugars together. 3. Beat in eggs and vanilla. 4. Mix in dry ingredients. 5. Fold in chocolate chips. 6. Drop spoonfuls onto baking sheet. 7. Bake for 10-12 minutes.',
        preparationTime: 30,
        servings: 24,
      },
      {
        name: 'Caprese Salad',
        description:
          'A fresh Italian salad featuring ripe tomatoes, creamy mozzarella, and fragrant basil.',
        ingredients:
          'Tomatoes, fresh mozzarella, basil leaves, olive oil, balsamic vinegar, salt, pepper',
        instructions:
          '1. Slice tomatoes and mozzarella. 2. Arrange on a platter, alternating slices. 3. Tuck basil leaves between slices. 4. Drizzle with olive oil and balsamic vinegar. 5. Sprinkle with salt and pepper. 6. Serve immediately.',
        preparationTime: 15,
        servings: 4,
      },
    ],
    Event: [
      {
        name: 'Spring Dinner Party',
        eventDate: '2024-04-15T19:00:00',
        location: "Emily's House",
        notes:
          'Celebrated the arrival of spring with friends. Tried new vegetarian recipes and enjoyed a relaxed evening outdoors.',
      },
      {
        name: 'Thanksgiving Feast',
        eventDate: '2023-11-23T17:30:00',
        location: "Grandma's Place",
        notes:
          'Traditional Thanksgiving dinner with family. Turkey was a hit, and everyone brought their favorite side dish.',
      },
      {
        name: 'Birthday Brunch',
        eventDate: '2024-02-10T11:00:00',
        location: 'The Garden Cafe',
        notes:
          'Surprised Sarah for her birthday. Served pancakes, fruit salad, and mimosas. Lots of laughter and great food.',
      },
      {
        name: 'Summer BBQ',
        eventDate: '2023-07-08T16:00:00',
        location: 'Central Park',
        notes:
          'Outdoor barbecue with friends and family. Grilled burgers, hot dogs, and veggie skewers. Played games and enjoyed the sunshine.',
      },
      {
        name: "New Year's Eve Dinner",
        eventDate: '2023-12-31T20:00:00',
        location: "Liam's Apartment",
        notes:
          'Rang in the new year with a fancy dinner and champagne. Tried a new dessert recipe and watched fireworks at midnight.',
      },
    ],
    Guest: [
      {
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        phoneNumber: '+1-555-123-4567',
      },
      {
        name: 'Brian Lee',
        email: 'brian.lee@example.com',
        phoneNumber: '+1-555-234-5678',
      },
      {
        name: 'Carmen Diaz',
        email: 'carmen.diaz@example.com',
        phoneNumber: '+1-555-345-6789',
      },
      {
        name: 'David Patel',
        email: 'david.patel@example.com',
        phoneNumber: '+1-555-456-7890',
      },
      {
        name: 'Emily Chen',
        email: 'emily.chen@example.com',
        phoneNumber: '+1-555-567-8901',
      },
    ],
    Eventrecipe: [
      {
        modifications:
          'Reduced the amount of salt by half and added extra garlic.',
        rating: 5,
        notes:
          'Everyone loved the flavor, especially with the garlic enhancement.',
      },
      {
        modifications:
          'Substituted almond milk for regular milk to accommodate lactose intolerance.',
        rating: 4,
        notes: 'Texture was slightly different but still very tasty.',
      },
      {
        modifications: 'Used gluten-free pasta instead of regular pasta.',
        rating: 3,
        notes:
          'Some guests noticed the difference, but overall it was well received.',
      },
      {
        modifications: 'Added fresh basil and oregano from the garden.',
        rating: 5,
        notes: 'Herbs made the dish very aromatic and flavorful.',
      },
      {
        modifications: 'Omitted chili flakes to make it kid-friendly.',
        rating: 4,
        notes: 'Kids enjoyed it, but some adults missed the heat.',
      },
    ],
  },
};
export default data;
