//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Game: [
      {
        Title: 'Space Invaders',
        Genre: 'Arcade',
        ReleaseDate: '1978-06-01T00:00:00Z',
        Description:
          'Space Invaders is a classic arcade game where players control a laser cannon to defeat rows of alien invaders.',
      },
      {
        Title: 'The Legend of Zelda',
        Genre: 'Action-Adventure',
        ReleaseDate: '1986-02-21T00:00:00Z',
        Description:
          'The Legend of Zelda is an action-adventure game centered around Link, a hero tasked with rescuing Princess Zelda and battling the evil Gannon.',
      },
      {
        Title: 'Super Mario Bros.',
        Genre: 'Platform',
        ReleaseDate: '1985-09-13T00:00:00Z',
        Description:
          'Super Mario Bros. is a platform game where players navigate Mario (or Luigi) through the Mushroom Kingdom to save Princess Toadstool.',
      },
      {
        Title: 'Final Fantasy VII',
        Genre: 'RPG',
        ReleaseDate: '1997-01-31T00:00:00Z',
        Description:
          'Final Fantasy VII is a role-playing game that follows Cloud Strife and his allies as they battle against the corrupt megacorporation Shinra, and the rogue former Shinra soldier Sephiroth.',
      },
      {
        Title: 'Minecraft',
        Genre: 'Sandbox',
        ReleaseDate: '2011-11-18T00:00:00Z',
        Description:
          'Minecraft is a sandbox game that allows players to build constructions out of textured cubes in a 3D procedurally generated world.',
      },
    ],
    Player: [
      {
        Name: 'Alex Johnson',
        Age: 27,
        Email: 'alex.johnson@example.com',
        Username: 'alexj27',
      },
      {
        Name: 'Bethany Huang',
        Age: 32,
        Email: 'bethany.huang@example.com',
        Username: 'bethhuang',
      },
      {
        Name: 'Carlos Gomez',
        Age: 24,
        Email: 'carlos.gomez@example.com',
        Username: 'cgomez24',
      },
      {
        Name: 'Diana Smith',
        Age: 29,
        Email: 'diana.smith@example.com',
        Username: 'dsmith',
      },
      {
        Name: 'Evan Wright',
        Age: 35,
        Email: 'evan.wright@example.com',
        Username: 'wrightevan',
      },
    ],
    GameSession: [
      { Game: 1, Players: 3, Date: '2023-04-01T14:00:00Z', Duration: 120 },
      { Game: 2, Players: 4, Date: '2023-04-02T16:30:00Z', Duration: 90 },
      { Game: 3, Players: 2, Date: '2023-04-03T18:00:00Z', Duration: 60 },
      { Game: 4, Players: 5, Date: '2023-04-04T20:00:00Z', Duration: 150 },
      { Game: 5, Players: 3, Date: '2023-04-05T15:00:00Z', Duration: 180 },
    ],
    Score: [
      { gameSession: 1, player: 1, scoreValue: 150 },
      { gameSession: 2, player: 2, scoreValue: 200 },
      { gameSession: 3, player: 3, scoreValue: 175 },
      { gameSession: 4, player: 4, scoreValue: 220 },
      { gameSession: 5, player: 5, scoreValue: 190 },
    ],
  },
};
export default data;
