//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Funds: {
      name: 'Funds',
      fields: {
        FundName: 'Fund Name',
        FundManager: 'Fund Manager',
        FundType: 'Fund Type',
        FundDescription: 'Fund Description',
        FundStartDate: 'Fund Start Date',
        FundSize: 'Fund Size',
        FundStatus: 'Fund Status',
        id: 'id',
      },
    },
    Investors: {
      name: 'Investors',
      fields: {
        InvestorName: 'Investor Name',
        InvestorType: 'Investor Type',
        InvestorContact: 'Investor Contact',
        InvestorAddress: 'Investor Address',
        InvestorInvestmentAmount: 'Investor Investment Amount',
        InvestorInvestmentDate: 'Investor Investment Date',
        InvestorStatus: 'Investor Status',
        id: 'id',
      },
    },
    Transactions: {
      name: 'Transactions',
      fields: {
        TransactionID: 'Transaction Id',
        TransactionDate: 'Transaction Date',
        TransactionType: 'Transaction Type',
        TransactionAmount: 'Transaction Amount',
        TransactionFund: 'Transaction Fund',
        TransactionInvestor: 'Transaction Investor',
        TransactionDescription: 'Transaction Description',
        id: 'id',
      },
    },
    Applications: {
      name: 'Applications',
      fields: {
        applicationName: 'Application Name',
        applicationIndustry: 'Application Industry',
        applicationDescription: 'Application Description',
        applicationFeatures: 'Application Features',
        applicationStatus: 'Application Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Funds: {
      name: 'Funds (fr)',
      fields: {
        FundName: 'Fund Name (fr)',
        FundManager: 'Fund Manager (fr)',
        FundType: 'Fund Type (fr)',
        FundDescription: 'Fund Description (fr)',
        FundStartDate: 'Fund Start Date (fr)',
        FundSize: 'Fund Size (fr)',
        FundStatus: 'Fund Status (fr)',
        id: 'id',
      },
    },
    Investors: {
      name: 'Investors (fr)',
      fields: {
        InvestorName: 'Investor Name (fr)',
        InvestorType: 'Investor Type (fr)',
        InvestorContact: 'Investor Contact (fr)',
        InvestorAddress: 'Investor Address (fr)',
        InvestorInvestmentAmount: 'Investor Investment Amount (fr)',
        InvestorInvestmentDate: 'Investor Investment Date (fr)',
        InvestorStatus: 'Investor Status (fr)',
        id: 'id',
      },
    },
    Transactions: {
      name: 'Transactions (fr)',
      fields: {
        TransactionID: 'Transaction Id (fr)',
        TransactionDate: 'Transaction Date (fr)',
        TransactionType: 'Transaction Type (fr)',
        TransactionAmount: 'Transaction Amount (fr)',
        TransactionFund: 'Transaction Fund (fr)',
        TransactionInvestor: 'Transaction Investor (fr)',
        TransactionDescription: 'Transaction Description (fr)',
        id: 'id',
      },
    },
    Applications: {
      name: 'Applications (fr)',
      fields: {
        applicationName: 'Application Name (fr)',
        applicationIndustry: 'Application Industry (fr)',
        applicationDescription: 'Application Description (fr)',
        applicationFeatures: 'Application Features (fr)',
        applicationStatus: 'Application Status (fr)',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    Funds: {
      name: 'Funds (gr)',
      fields: {
        FundName: 'Fund Name (gr)',
        FundManager: 'Fund Manager (gr)',
        FundType: 'Fund Type (gr)',
        FundDescription: 'Fund Description (gr)',
        FundStartDate: 'Fund Start Date (gr)',
        FundSize: 'Fund Size (gr)',
        FundStatus: 'Fund Status (gr)',
        id: 'id',
      },
    },
    Investors: {
      name: 'Investors (gr)',
      fields: {
        InvestorName: 'Investor Name (gr)',
        InvestorType: 'Investor Type (gr)',
        InvestorContact: 'Investor Contact (gr)',
        InvestorAddress: 'Investor Address (gr)',
        InvestorInvestmentAmount: 'Investor Investment Amount (gr)',
        InvestorInvestmentDate: 'Investor Investment Date (gr)',
        InvestorStatus: 'Investor Status (gr)',
        id: 'id',
      },
    },
    Transactions: {
      name: 'Transactions (gr)',
      fields: {
        TransactionID: 'Transaction Id (gr)',
        TransactionDate: 'Transaction Date (gr)',
        TransactionType: 'Transaction Type (gr)',
        TransactionAmount: 'Transaction Amount (gr)',
        TransactionFund: 'Transaction Fund (gr)',
        TransactionInvestor: 'Transaction Investor (gr)',
        TransactionDescription: 'Transaction Description (gr)',
        id: 'id',
      },
    },
    Applications: {
      name: 'Applications (gr)',
      fields: {
        applicationName: 'Application Name (gr)',
        applicationIndustry: 'Application Industry (gr)',
        applicationDescription: 'Application Description (gr)',
        applicationFeatures: 'Application Features (gr)',
        applicationStatus: 'Application Status (gr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
