//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Book: {
      name: 'Book',
      fields: {
        title: 'Title',
        author: 'Author',
        releaseDate: 'Release Date',
        description: 'Description',
        ISBN: 'Isbn',
        coverImage: 'Cover Image',
        publisher: 'Publisher',
        language: 'Language',
        pages: 'Pages',
        averageRating: 'Average Rating',
        id: 'id',
      },
    },
    Authors: {
      name: 'Authors',
      fields: {
        authorName: 'Author Name',
        genre: 'Genre',
        nationality: 'Nationality',
        id: 'id',
      },
    },
    Members: {
      name: 'Members',
      fields: {
        Name: 'Name',
        Email: 'Email',
        Address: 'Address',
        PhoneNumber: 'Phone Number',
        DateOfBirth: 'Date Of Birth',
        MembershipStatus: 'Membership Status',
        JoiningDate: 'Joining Date',
        MembershipType: 'Membership Type',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Book: {
      name: 'Book (fr)',
      fields: {
        title: 'Title (fr)',
        author: 'Author (fr)',
        releaseDate: 'Release Date (fr)',
        description: 'Description (fr)',
        ISBN: 'Isbn (fr)',
        coverImage: 'Cover Image (fr)',
        publisher: 'Publisher (fr)',
        language: 'Language (fr)',
        pages: 'Pages (fr)',
        averageRating: 'Average Rating (fr)',
        id: 'id',
      },
    },
    Authors: {
      name: 'Authors (fr)',
      fields: {
        authorName: 'Author Name (fr)',
        genre: 'Genre (fr)',
        nationality: 'Nationality (fr)',
        id: 'id',
      },
    },
    Members: {
      name: 'Members (fr)',
      fields: {
        Name: 'Name (fr)',
        Email: 'Email (fr)',
        Address: 'Address (fr)',
        PhoneNumber: 'Phone Number (fr)',
        DateOfBirth: 'Date Of Birth (fr)',
        MembershipStatus: 'Membership Status (fr)',
        JoiningDate: 'Joining Date (fr)',
        MembershipType: 'Membership Type (fr)',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    Book: {
      name: 'Book (gr)',
      fields: {
        title: 'Title (gr)',
        author: 'Author (gr)',
        releaseDate: 'Release Date (gr)',
        description: 'Description (gr)',
        ISBN: 'Isbn (gr)',
        coverImage: 'Cover Image (gr)',
        publisher: 'Publisher (gr)',
        language: 'Language (gr)',
        pages: 'Pages (gr)',
        averageRating: 'Average Rating (gr)',
        id: 'id',
      },
    },
    Authors: {
      name: 'Authors (gr)',
      fields: {
        authorName: 'Author Name (gr)',
        genre: 'Genre (gr)',
        nationality: 'Nationality (gr)',
        id: 'id',
      },
    },
    Members: {
      name: 'Members (gr)',
      fields: {
        Name: 'Name (gr)',
        Email: 'Email (gr)',
        Address: 'Address (gr)',
        PhoneNumber: 'Phone Number (gr)',
        DateOfBirth: 'Date Of Birth (gr)',
        MembershipStatus: 'Membership Status (gr)',
        JoiningDate: 'Joining Date (gr)',
        MembershipType: 'Membership Type (gr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
